INSERT INTO OEUVRE (id_oeuvre, description, genre, score) VALUES
('O1', 'Un grand classique de la littérature', 'Roman', '9.5'),
('O2', 'Une œuvre philosophique et engagée', 'Essai', '8.7'),
('O3', 'Un chef-dœuvre du théâtre français', 'Théâtre', '9.2'),
('O4', 'Un recueil de nouvelles', 'Nouvelles', '8.9'),
('O5', 'Un roman historique fascinant', 'Historique', '9.1'),
('O6', 'Une épopée poétique', 'Poésie', '8.5'),
('O7', 'Un roman daventure captivant', 'Aventure', '9.0'),
('O8', 'Un thriller psychologique intense', 'Thriller', '8.8'),
('O9', 'Un manuel de philosophie', 'Manuel', '8.6'),
('O10', 'Un essai sur la société contemporaine', 'Essai', '9.0'),
('O11', 'Une biographie inspirante', 'Biographie', '9.3'),
('O12', 'Un roman de science-fiction visionnaire', 'Science-fiction', '8.9'),
('O13', 'Une tragédie classique', 'Théâtre', '9.2'),
('O14', 'Un conte philosophique', 'Conte', '9.4'),
('O15', 'Une satire politique et sociale', 'Satire', '8.8');
