INSERT INTO PAYS (id_pays, pays, langue, nationalite) VALUES
('FR', 'France', 'Français', 'Française'),
('US', 'United States', 'English', 'American'),
('DE', 'Germany', 'German', 'German'),
('ES', 'Spain', 'Spanish', 'Spanish'),
('IT', 'Italy', 'Italian', 'Italian'),
('LB', 'Lebanon', 'Arabic', 'Lebanese'),
('NC', 'Nouvelle Caledonie', 'Français', 'Française'),
('SY', 'Syria', 'Arabic', 'Syrian'),
('AU', 'Australia', 'English', 'Australian'),
('NZ', 'New Zealand', 'English', 'New Zealander'),
('TR', 'Turkey', 'Turkish', 'Turkish'),
('JP', 'Japan', 'Japanese', 'Japanese'),
('CN', 'China', 'Chinese', 'Chinese'),
('IN', 'India', 'Hindi', 'Indian'),
('BR', 'Brazil', 'Portuguese', 'Brazilian'),
('RU', 'Russia', 'Russian', 'Russian'),
('CA', 'Canada', 'English/French', 'Canadian'),
('MX', 'Mexico', 'Spanish', 'Mexican'),
('ZA', 'South Africa', 'English', 'South African'),
('KR', 'South Korea', 'Korean', 'South Korean'),
('NG', 'Nigeria', 'English', 'Nigerian'),
('RS', 'Serbia', 'Serbian', 'Serbian'),
('BA', 'Bosnia and Herzegovina', 'Bosnian', 'Bosnian'),
('ME', 'Montenegro', 'Montenegrin', 'Montenegrin'),
('AL', 'Albania', 'Albanian', 'Albanian'),
('MK', 'Macedonia', 'Macedonian', 'Macedonian'),
('BG', 'Bulgaria', 'Bulgarian', 'Bulgarian'),
('RO', 'Romania', 'Romanian', 'Romanian'),
('MD', 'Moldova', 'Romanian', 'Moldovan'),
('UA', 'Ukraine', 'Ukrainian', 'Ukrainian'),
('BY', 'Belarus', 'Belarusian', 'Belarusian'),
('LT', 'Lithuania', 'Lithuanian', 'Lithuanian'),
('LV', 'Latvia', 'Latvian', 'Latvian'),
('EE', 'Estonia', 'Estonian', 'Estonian'),
('IE', 'Ireland', 'English', 'Irish'),
('IS', 'Iceland', 'Icelandic', 'Icelandic');